### ISSUE TITLE
[demo] Allow chunk sizes to be configurable when deploying models

### ISSUE THREAD

**Issue by juharris** [microsoft/0xDeCA10B#105]
The chunk sizes are set pretty low but it's still possible that people run out of gas when deploying models.
For now, people should confirm that deployment works on a test chain before deploying elsewhere.

**Comment by vaibhavarora102** [comment]
Hi @juharris 
I would like to contribute to this issue.
I am comfortable with Machine learning and stuff but didn't work with blockchain till now, but to the best of my knowledge what I understand is this task doesn't require knowledge of blockchain. So with that respect, I would like to go with this issue.

can you pls direct me to the respective folder or file upon which I require to work and some info regarding setting up this project in the local environment.
thanks.

**Comment by juharris** [comment]
Thanks for reaching out! That's right, this doesn't require deep blockchain knowledge but it's a good intro because it involves the code that we use to deploy the smart contracts for the machine learning models.
The two files that need changes are:
* https://github.com/microsoft/0xDeCA10B/blob/main/demo/client/src/ml-models/deploy-model.ts and 
* https://github.com/microsoft/0xDeCA10B/blob/main/demo/client/src/ml-models/deploy-model-node.js

Just search for "chunkSize" and you'll see how there are hard-coded chunkSizes. For deploy-model.ts, you can add `initializeChunkSize` and `chunkSize` to the `options`. Keep the current values as the defaults.
For deploy-model-node.js, you can introduce an `options` parameter like the other file has.
Let me know if you need more clarification or would like to have a call.

Thanks again for your interest!

**Comment by vaibhavarora102** [comment]
Thank you, for telling the whole overview,
I will surely try to contribute to this, can you please assign me this issue?

and yes once after going through files if I found and the difficulty over understanding or something else will surely ask from you via GitHub comments or could surely have a call
thanks

**Comment by juharris** [comment]
Awesome!

**Comment by vaibhavarora102** [comment]
@juharris  kindly check,
I had made some changes as suggested by you

**Comment by vaibhavarora102** [comment]
@juharris  Shall I proceed with the node.js file if deploy-model.ts is in the right format now, 
And yes can you pls guide me that which options are required to include in options (the ones that are mentioned in the function itself or all that I could see in the deploy-model.ts file)

**Comment by juharris** [comment]
The .ts file looks good!

For deploy-model-node.js, the only options needed are `toFloat`, `initialChunkSize`, and `chunkSize`.

**Comment by vaibhavarora102** [comment]
Do I need to put options in form of parameters to the function or as under-promise as done in the .ts file?

**Comment by juharris** [comment]
I'm not sure what you mean by under-promise but you should do it like it was done in the .ts file: with an `options` parameter as an object. So you can also remove the `toFloat` parameter since it will be in the `options`.
This breaks the current API but I think that's okay since I doubt anyone is using it. There might be places in our code where we call the method but I don't think those places will break but I don't think they're setting the `toFloat` value.

**Comment by vaibhavarora102** [comment]
@juharris Kindly check the changes made in node.js

**Comment by vaibhavarora102** [comment]
@juharris Thanks a lot for merging
