### ISSUE TITLE
[Simulation] -> Bokeh server application does not exist

### ISSUE THREAD

**Issue by Karthikay2002** [microsoft/0xDeCA10B#130]
Hi! I've recently started working and learning on SUM. I'm currently stuck with running the Simulation steps.

To direct you to the steps I've followed:

1 - I tried running the "docker run --rm -it -p 5006:5006 -v %cd%:/root/workspace/0xDeCA10B/simulation --name decai-simulation mcr.microsoft.com/samples/blockchain-ai/0xdeca10b-simulation bash" comman on my Git Cmd.
2 - Got my docker file up and running
3 - I then tried running "bokeh serve decai/simulation/simulate_imdb_perceptron.py"

This is where I got stuck and I get this:
![image](https://user-images.githubusercontent.com/54672017/133315500-1be01bcc-5862-4763-bd3d-2212aafdac83.png)

I did quite some searches on google and tried some codes with regards to bokeh, and none worked. 

Would be great if someone can guide me with what has happened and what needs to be done, new to this sort of tech!

Thank You

**Comment by juharris** [comment]
Thanks for trying out the code! The error is saying that the simulate_imdb... file doesn't exist.
You need to clone the repo and run the `docker run` command from the `0xDeCA10B/simulation` folder.

**Comment by Karthikay2002** [comment]
Thanks for replying back Justin.

Exactly! That's the problem!
![image](https://user-images.githubusercontent.com/54672017/133370528-3ed3ee40-f92e-4154-b12d-91b05967c2d3.png)

I've downloaded all the files required, and arranged it as required. And yet, it says that it is not found. 

Confused with what's going on.

**Comment by juharris** [comment]
Like I said, run the `docker run` command from the 0xDeCA10B/simulation folder. You ran the command from the folder called "tonys".
