### ISSUE TITLE
demo deployment failed

### ISSUE THREAD

**Issue by historyboy** [microsoft/0xDeCA10B#68]
Hello author. When I installed your demo, I encountered two problems, 1: I want to know under what environment do you run, window powershell or linux? 2: I am running under Linux and running to Listening on 0.0.0.0:7545 when executing to the yarn blockchain, I haven't executed any further. Attempt to execute yarn client or yarn server also fails

**Comment by juharris** [comment]
Hey thanks for trying the project!
It works on Linux. I usually use WSL but there's also the Docker containers which are Linux based.

What are the errors you get when you run `yarn client` or `yarn server`? Can you send a screenshot of the console or copy and paste from the console to here?

**Comment by historyboy** [comment]
- ![image](https://user-images.githubusercontent.com/23580988/71009470-3e3e5380-2125-11ea-829b-6463e0a5be9e.png)
Thank you very much for your reply. When I execute the "yarn blockchain" command, the terminal runs to Listening on 0.0.0.0:7545 and will not execute it, as shown in the screenshot. When I execute "yarn client" or "yarn server", I get errors, such as screenshot
![image](https://user-images.githubusercontent.com/23580988/71010195-6f6b5380-2126-11ea-96ad-be46f00da069.png)。Looking forward to your reply

**Comment by juharris** [comment]
Weird, it looks like some files are missing.
Can you run `ls -l; ls -l client/` in your `demo/` folder.
For example, here's how mine looks (it's okay if you're missing certain files, you'll get them when we get this running):
```
$ ls -l; ls -l client/
total 12586
drwxr-xr-x 1 juharri 1049089      0 Dec 16 17:20 blockchain_db
drwxr-xr-x 1 juharri 1049089      0 Dec 13 15:41 client
-rw-r--r-- 1 juharri 1049089  20480 Dec  4 11:37 db.sqlite
-rw-r--r-- 1 juharri 1049089    524 Dec  4 12:52 Dockerfile
drwxr-xr-x 1 juharri 1049089      0 Dec 12 14:33 node_modules
-rw-r--r-- 1 juharri 1049089    946 Dec 12 14:33 package.json
-rw-r--r-- 1 juharri 1049089   6644 Nov 29 09:56 README.md
-rw-r--r-- 1 juharri 1049089   3745 Dec 17 10:47 server.js
-rw-r--r-- 1 juharri 1049089    977 Dec  3 13:21 service.Dockerfile
-rwxr-xr-x 1 juharri 1049089    238 Nov 28 14:26 setup.sh
-rwxr-xr-x 1 juharri 1049089    807 Aug 20 15:05 setup_libs.sh
-rw-r--r-- 1 juharri 1049089 120838 Dec 12 14:33 yarn.lock
total 1096
drwxr-xr-x 1 juharri 1049089      0 Sep  3 14:40 contracts
-rwxr-xr-x 1 juharri 1049089     74 Dec  9 17:07 deploy_client.sh
drwxr-xr-x 1 juharri 1049089      0 Nov 18 09:46 migrations
drwxr-xr-x 1 juharri 1049089      0 Dec 12 14:37 node_modules
-rw-r--r-- 1 juharri 1049089   1585 Dec 12 14:35 package.json
drwxr-xr-x 1 juharri 1049089      0 Dec  9 15:21 public
drwxr-xr-x 1 juharri 1049089      0 Dec 16 14:17 src
-rwxr-xr-x 1 juharri 1049089    139 Nov 20 16:36 start_prod.sh
drwxr-xr-x 1 juharri 1049089      0 Dec  4 12:52 test
-rwxr-xr-x 1 juharri 1049089    755 Dec  4 12:52 test.sh
-rw-r--r-- 1 juharri 1049089    484 Nov 20 12:47 truffle.js
-rw-r--r-- 1 juharri 1049089    497 Nov 28 13:58 tsconfig.json
-rw-r--r-- 1 juharri 1049089 563012 Dec 12 14:37 yarn.lock

**Comment by juharris** [comment]
Oh is this from the Docker container? Did you run the `docker run` command from inside the `demo/` folder?
Make sure you do and if you did, then it's possible that the `${PWD}` part isn't working right on Linux. Sometimes changing `${PWD}` to `/${PWD}` or `//${PWD}` helps.

**Comment by historyboy** [comment]
![image](https://user-images.githubusercontent.com/23580988/71092251-db5ec200-21e1-11ea-8ed5-ecda4d118f8c.png)Inconsistent with the total you show，I execute it in a Docker container。

**Comment by juharris** [comment]
That's ok if the totals don't match.
Ok I see the files there but your prompt is different from the one you showed before. This one doesn't look like it's in the docker container.
Did you run `docker run ...` from inside the demo folder?

**Comment by historyboy** [comment]
![image](https://user-images.githubusercontent.com/23580988/71094715-6346cb00-21e6-11ea-8c29-d68d981f9dda.png)This step is already running docker

**Comment by juharris** [comment]
Yes, in the last picture Docker is running as I can tell from the prompt with "root@bf..."
so now run `ls -l; ls -l client/`

**Comment by historyboy** [comment]
![image](https://user-images.githubusercontent.com/23580988/71095621-e1f03800-21e7-11ea-8391-a441412ef74b.png)The result is this.I still have two questions: 1 I saw the command you executed in the powershell window in the demo video. This part is not clear. Shouldn't it be executed under linux? 2: Does Chrome in the demo (running MATEMASK) also run on Linux? ?Thanks for the answer

**Comment by juharris** [comment]
Aha ok so files are missing in the picture.
So there are a few things that could be going wrong here. I see that you changed the values `-v` from the command in the README. First try it exactly as it is in the README.
If that doesn't work then you can try changing `${PWD}` as I described above.
I did execute the `docker run` command in PowerShell but once I did that I am then running commands inside the Docker container as if I'm using Linux.
Chrome stills runs on Windows but it is able to communicate with the Linux services running in the Docker container because of the `-p 3000:3000 -p 5387:5387 -p 7545:7545` options which map ports from the running Docker container.

**Comment by juharris** [comment]
BTW I know it says the `yarn server` command is optional but I realized it's not actually optional for the first time setup! I'm going to correct that now so the changing will come in a pull request probably later today. In the meantime, do run the `yarn server` command even though the step says that it is optional.

**Comment by juharris** [comment]
The above instructions should solve the problem. Please re-open if you're still having issues.
