### ISSUE TITLE
WSL Deployment Consulting

### ISSUE THREAD

**Issue by historyboy** [microsoft/0xDeCA10B#89]
Hello, I used to run the linux virtual machine under vmware. The installation steps of your installation were unsuccessful. Now I want to implement it through WSL to see if I can do it. However, I have a few questions to ask you now: 1: What necessary configurations need to be prepared in WSL (except npm), can you provide detailed command steps? 2: Is docker installed in WSL? , You did not involve the installation of docker in the video demo. 3: I saw that your video demo used powershell to actually execute the command. I don't understand this point. How is it related to WSL? I am a beginner and appreciate your interest in this project. I hope I can run through it myself.
 Looking forward to your reply, 
                                                                                                              sincerely thanks

**Comment by juharris** [comment]
Thanks for your interest in the project!

What were the errors that you got when using VMware?

I normally use WSL but I used the Docker container in the demo video because I thought it would be easier for others to set up the Docker container.

1. For WSL, I don't think there's anything too special that I needed to do set this up other than installing `npm`. The commands in the [Dockerfile](https://github.com/microsoft/0xDeCA10B/blob/master/demo/Dockerfile) might be helpful if you run into any issues.
2. I don't use Docker through WSL (I don't even think that's possible).
3. I ran [`docker`](https://docs.docker.com/docker-for-windows/install/) through [PowerShell](https://aka.ms/pscore6-docs) since that's usually the recommended way to run Docker commands on Windows. You can run Docker commands in the typical `cmd` Command Prompt on Windows or in Git Bash (which you should have if you have Git) but I used PowerShell for the video because I thought it would be more Windows friendly.

Let me know if you have any other questions, I'm happy to help!

**Comment by historyboy** [comment]
Thank you very much for your patience
&nbsp; &nbsp; The third point, do you mean that docker is running on Windows system, and then execute commands through powershell? ? Or is docker running on a linux system and then executing commands through powershell? ?
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Thank you for your help



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Justin D. Harris"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 晚上9:48
收件人:&nbsp;"microsoft/0xDeCA10B"<0xDeCA10B@noreply.github.com&gt;;
抄送:&nbsp;"知了"<1515945630@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/0xDeCA10B] WSL Deployment Consulting (#89)





 
Thanks for your interest in the project!
 
What were the errors that you got when using VMware?
 
I normally use WSL but I used the Docker container in the demo video because I thought it would be easier for others to set up the Docker container.
  
For WSL, I don't think there's anything too special that I needed to do set this up other than installing npm. The commands in the Dockerfile might be helpful if you run into any issues.
 
I don't use Docker through WSL (I don't even think that's possible).
 
I ran docker through PowerShell since that's usually the recommended way to run Docker commands on Windows. You can run Docker commands in the typical cmd Command Prompt on Windows or in Git Bash (which you should have if you have Git) but I used PowerShell for the video because I thought it would be more Windows friendly.
  
Let me know if you have any other questions, I'm happy to help!

**Comment by juharris** [comment]
Docker is running on Windows. I open PowerShell or Git Bash and then start the Docker container with `docker run ...`. Now when I run commands inside the container, it looks as if I'm running a Linux machine:
![image](https://user-images.githubusercontent.com/1594505/77767608-b74c2180-7017-11ea-8f27-d154688877d6.png)

**Comment by historyboy** [comment]
Thank you very much, I understand, I will try to deploy again, there is a problem in consulting you
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; sincere thanks





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Justin D. Harris"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月27日(星期五) 晚上10:43
收件人:&nbsp;"microsoft/0xDeCA10B"<0xDeCA10B@noreply.github.com&gt;;
抄送:&nbsp;"知了"<1515945630@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/0xDeCA10B] WSL Deployment Consulting (#89)





 
Docker is running on Windows. I open PowerShell or Git Bash and then start the Docker container with docker run .... Now when I run commands inside the container, it looks as if I'm running a Linux machine:

**Comment by historyboy** [comment]
Thank you for your patience. I have already installed the docker program. Since I do n’t know much about docker, there are still some doubts during the operation. 1. Is the demo code file you wrote stored in the Windows system or docker during execution? How about it? If stored in Windows, what command does powershell execute? If you want to copy to docker, what command is used for copying? 2: Does powershell need to be set in advance to execute docker commands? 3: Can you provide what commands did you execute before this step (red line)?
![DLBO{0U9Q@X38IO4F)KDQ{H](https://user-images.githubusercontent.com/23580988/77786390-b4dddc00-7098-11ea-9bd4-fda8aff96136.png)

                                                                                       Sincerely thank you

**Comment by juharris** [comment]
1. The code is stored in Windows. I clone the GitHub repo in Windows and use the `-v` option in the `docker run` command to mount the code on Windows to a folder in the Docker container.
2. Nothing very special needs to be done in PowerShell before running that command.
3. Before running that command, I installed Docker for Windows, I started Docker in Windows (by clicking on the Docker Desktop icon), then changed the directory to the `demo` folder: `cd .\workspace\0xDeCA10B\demo\`.

**Comment by historyboy** [comment]
Thank you, I'll try again.



---Original---

**Comment by historyboy** [comment]
Hello, this time I use docker to execute the program. When I execute to step 4, it always generates eth_blockNumber, and it does not continue to execute. The following are all the commands I executed, please help me analyze the problem.






&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; sincere thanks





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Justin D. Harris"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月28日(星期六) 凌晨2:19
收件人:&nbsp;"microsoft/0xDeCA10B"<0xDeCA10B@noreply.github.com&gt;;
抄送:&nbsp;"知了"<1515945630@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/0xDeCA10B] WSL Deployment Consulting (#89)





  
The code is stored in Windows. I clone the GitHub repo in Windows and use the -v option in the docker run command to mount the code on Windows to a folder in the Docker container.
 
Nothing very special needs to be done in PowerShell before running that command.
 
Before running that command, I installed Docker for Windows, I started Docker in Windows (by clicking on the Docker Desktop icon), then changed the directory to the demo folder: cd .\workspace\0xDeCA10B\demo\.

**Comment by historyboy** [comment]
Hello, when I open another powershell to execute the yarn client or yarn server, I get the following error (of course, this is executed without the yarn blockchain being executed)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 

&nbsp; sincere thanks





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Justin D. Harris"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月28日(星期六) 凌晨2:19
收件人:&nbsp;"microsoft/0xDeCA10B"<0xDeCA10B@noreply.github.com&gt;;
抄送:&nbsp;"知了"<1515945630@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/0xDeCA10B] WSL Deployment Consulting (#89)





  
The code is stored in Windows. I clone the GitHub repo in Windows and use the -v option in the docker run command to mount the code on Windows to a folder in the Docker container.
 
Nothing very special needs to be done in PowerShell before running that command.
 
Before running that command, I installed Docker for Windows, I started Docker in Windows (by clicking on the Docker Desktop icon), then changed the directory to the demo folder: cd .\workspace\0xDeCA10B\demo\.

**Comment by historyboy** [comment]
Hello, your program has been successfully deployed, but you have updated the version. This is the result of my successful deployment.
 
![image](https://user-images.githubusercontent.com/23580988/77853805-b0403180-7218-11ea-8e86-2a97588b4997.png)

I want to deploy and get your previous version of IMDB review sentiment classifier, which is the result shown in your video demo. I keep the previous code now. Can you tell me what files need to be modified? ?
![image](https://user-images.githubusercontent.com/23580988/77853815-cd750000-7218-11ea-8e47-fad8ca25abb9.png)
                                                                                                      sincere thanks

**Comment by historyboy** [comment]
Hello, I used the old code version to achieve this interface. 
![image](https://user-images.githubusercontent.com/23580988/77855043-8ab72600-7220-11ea-88f4-459058981af4.png)

 I want to go to the previous interface, can you tell me how to change it?
    
![image](https://user-images.githubusercontent.com/23580988/77855046-9571bb00-7220-11ea-862a-21b55eb2d3be.png)

        Looking forward to your recovery thank you very much

**Comment by historyboy** [comment]
Hello, please trouble you again, do you still keep the deployment code of IMDB Review sentiment classifier (I always thought it was recently deployed), I want to achieve this, if you still have it, can you send me a copy ? If possible, please send to this email wyl15159@foxmail.com
                                                                                                Sincerely thank you

**Comment by juharris** [comment]
Cool I'm glad you got it running!
Did you follow the steps [here](https://github.com/microsoft/0xDeCA10B/tree/master/demo#server-optional) to start the server? The example models have their meta-data stored in that local server database so the easier way to use them is to follow the instructions in there.

If you did not start the server, then I suggest you do `yarn clean`. Then you can go through the setup steps of running `yarn blockchain`, `yarn server`, then `yarn client` all in separate byobu screens.

**Comment by historyboy** [comment]
Thank you very much for your guidance. I got it up and running and followed your demo steps. However, I want to achieve IMDB Review sentiment classifier (I always thought it was recently deployed), this is your video demo. Can you tell me what I can do to achieve this version for you?
                                                                                                                             Sincerely thank you

**Comment by historyboy** [comment]
Hello, this is a great project, I achieve IMDB Review sentiment classifier, thank you very much for your patience and help.
                                       sincere thanks

**Comment by juharris** [comment]
My pleasure! Let me know if you have any other questions or suggestions.

**Comment by historyboy** [comment]
OK, thank you for your patience and good health.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Justin D. Harris"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 上午10:03
收件人:&nbsp;"microsoft/0xDeCA10B"<0xDeCA10B@noreply.github.com&gt;;
抄送:&nbsp;"知了"<1515945630@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/0xDeCA10B] WSL Deployment Consulting (#89)





 
My pleasure! Let me know if you have any other questions or suggestions.
