### ISSUE TITLE
[demo]When I run the command "yarn client", somethings goes error which reminder me "bash: deploy_client.sh:No such file or directory".

### ISSUE THREAD

**Issue by fxm2019** [microsoft/0xDeCA10B#94]
[demo]When I run the command "yarn client", somethings goes error which reminder me "bash: deploy_client.sh:No such file or directory and error command failed with exit code 127". Then I check the file directory by "find -name deploy_client.sh", it's a pity that there is no this file. I want to know whether  there is that file?

**Comment by juharris** [comment]
Thanks for trying out the code!
Can you share more about how you're running it? As the [instructions ](https://github.com/microsoft/0xDeCA10B/tree/master/demo#setup) say, I recommend using Linux or Windows Subsystem for Linux (WSL). Otherwise, you can use the [Docker images](https://github.com/microsoft/0xDeCA10B/tree/master/demo#docker-setup).

**Comment by juharris** [comment]
As for that error message. The file deploy_client.sh is in the demo/client folder. I assume you ran that `find` command from the demo folder? The command `yarn client` will first do `cd client` where the file exists. I don't why `find` didn't find it.

**Comment by fxm2019** [comment]
Thanks for your reply!
I run this code with docker image downloaded in insturctions. I also run 'cd client' before running 'yarn client', but somthing goes wrong that there is ''error Command "client" not found.'' I check files in this docker images, actually there is no this deploy_client.sh. However, in your  github sorce code, this file exists. So I  doubt whether this docker images you make is not complete. If you are convenient, can I add your twitter so that I can send your some error images?
Thanks for your reply again sir!

**Comment by fxm2019** [comment]
@juharris
Thanks for your reply!
I run this code with docker image downloaded in insturctions. I also run 'cd client' before running 'yarn client', but somthing goes wrong that there is ''error Command "client" not found.'' I check files in this docker images, actually there is no this deploy_client.sh. However, in your github sorce code, this file exists. So I doubt whether this docker images you make is not complete. If you are convenient, can I add your twitter so that I can send your some error images?
Thanks for your reply again sir!

**Comment by juharris** [comment]
My twitter is `@jusharris` but I would rather discuss here so that others with the same problem can get help.
Can you show me the exact commands that you're running? You need to clone the repo before using the Docker container. Sorry if that's not clear, but I thought it would be because of the mount option (`-v`).

**Comment by juharris** [comment]
This demo should help you https://youtu.be/dVDNahN6iPs

**Comment by fxm2019** [comment]
I put my running process and error information in `DockerError.pdf`. Thanks for your checking!
[DockerError.pdf](https://github.com/microsoft/0xDeCA10B/files/5198544/DockerError.pdf)

**Comment by juharris** [comment]
Can you paste the commands into here? It will be easier for others to see.

**Comment by juharris** [comment]
Did you clone the repo before running the commands?

**Comment by fxm2019** [comment]
The error appears after I run `yarn client`, it remind me not find `deploy_client.sh` . But I run the codes in the docker you built and I also clone this repo. In this repo, the `deploy_client.sh` exists, but it doesn't in your docker. Below is my error information picture.
![DockerError1](https://user-images.githubusercontent.com/49747431/92691011-8026be00-f374-11ea-884a-65ffafc57468.png)
![DockerError2](https://user-images.githubusercontent.com/49747431/92691023-81f08180-f374-11ea-910f-f03fd4aa07c2.png)
![DockerError3](https://user-images.githubusercontent.com/49747431/92691026-82891800-f374-11ea-9a52-c4faf276e68d.png)

**Comment by juharris** [comment]
Can I see the `docker run` command that you used? There is an example in the README.md to copy.

**Comment by fxm2019** [comment]
I just copy this command in `README.md`. This command is `docker run --rm -it -p 3000:3000 -p 5387:5387 -p 7545:7545 -v :/root/workspace/demo -v /root/workspace/demo/node_modules -v /root/workspace/demo/client/node_modules --name decai-demo mcr.microsoft.com/samples/blockchain-ai/0xdeca10b-demo bash`
![1599746613(1)](https://user-images.githubusercontent.com/49747431/92741790-9010c300-f3b1-11ea-8703-4d3f22aca634.jpg)

**Comment by juharris** [comment]
You'll need to be in the demo folder when you run that `docker run` command. I clarified the steps in the instructions: https://github.com/microsoft/0xDeCA10B/blob/master/demo/README.md#docker-setup
Thanks for your patience.

**Comment by fxm2019** [comment]
Thanks for your answer! Sorry for this lower error, thanks again!

**Comment by juharris** [comment]
No problem. I'm glad that I could clarify the steps. Let me know if you have other questions.

**Comment by fxm2019** [comment]
I solve above problem,but I still encountered other errors. When I run 'yarn client' and `yarn server` , the error is as follows. I don't know whether is a `truffle` version problem. Since I'm a beginner in this field, so I'm glad for your help. Thanks for your kind reply~!
![1599794573(1)](https://user-images.githubusercontent.com/49747431/92852307-28925c00-f421-11ea-9d8c-b49b1d1a7f90.jpg)
![1599794606(1)](https://user-images.githubusercontent.com/49747431/92852390-3d6eef80-f421-11ea-96fb-767872c238dd.jpg)

**Comment by juharris** [comment]
Thanks for pointing that out. I got past that issue by making a small change. See #95 or just pull the latest master if that pull request gets merged.

**Comment by fxm2019** [comment]
Hi, sir. Sorry about testing again now! Now I encountered another problem. Still when I run `yarn client`, something went wrong as the below picture.
![compile_error](https://user-images.githubusercontent.com/49747431/94246724-b3f60c00-ff4e-11ea-9278-dabaa636e9b7.png)
It seems somthing went wrong in `deploy-model.ts` file. But this code is new to me. I'm looking forward to your help!! Thanks, sir!

**Comment by fxm2019** [comment]
> Hi, sir. Sorry about testing again now! Now I encountered another problem. Still when I run `yarn client`, something went wrong as the below picture.
> ![compile_error](https://user-images.githubusercontent.com/49747431/94246724-b3f60c00-ff4e-11ea-9278-dabaa636e9b7.png)
> It seems somthing went wrong in `deploy-model.ts` file. But this code is new to me. I'm looking forward to your help!! Thanks, sir!

I doubt whether this error occured due to typescript version, and my typescript version is `typescript@4.0.3`. Thanks for your check!

**Comment by juharris** [comment]
Hi, thanks for your interest and patience. This is already resolved in the master branch. I made #98 to resolve that. Like I said in #98, I don't know why the tests passed if this happened. Sorry.

**Comment by fxm2019** [comment]
Really Thanks! I have fixed this error and enter this web page. Thanks for your kind help. I will test this web application further. Now I am learning about Federated Learning based Blockchain. Further may I share some thoughts about this research with you and I'm glad to listen your thoughts about this field. Thanks for your help and patience, sir!

**Comment by juharris** [comment]
@fxm2019  Thanks for your interest! I have a few talks here: https://www.youtube.com/playlist?list=PLfC95bU1D4golf4QCdpPjpOJS87-K9eOQ
